// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmNXYWphNOtaxV9N5WyHh3EIvkl_b6pbg',
    appId: '1:216156008779:web:11756132498c2436dab8ce',
    messagingSenderId: '216156008779',
    projectId: 'login-b92b5',
    authDomain: 'login-b92b5.firebaseapp.com',
    storageBucket: 'login-b92b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBLRFeVjSqrNrRhIJqeQDKAvR8eI8c-8',
    appId: '1:216156008779:android:92007a0db9248205dab8ce',
    messagingSenderId: '216156008779',
    projectId: 'login-b92b5',
    storageBucket: 'login-b92b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepPBEaHHLaJKcXCVpaA3WQBiWPljJ31c',
    appId: '1:216156008779:ios:7e1fac65acb60ef8dab8ce',
    messagingSenderId: '216156008779',
    projectId: 'login-b92b5',
    storageBucket: 'login-b92b5.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
